[env]
platform = atmelavr
board = uno
framework = arduino
[env:xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
lib_deps =
    arduino-libraries/MIDI@^5.0.2
    lathoub/USB-MIDI@^1.0.1exit